package RandJLawFirm;

import static RandJLawFirm.FileChooser.getMediaDirectory;
import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import static java.nio.file.StandardCopyOption.*;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
//import static jdk.nashorn.internal.objects.NativeRegExp.source;
import java.awt.Desktop;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class AddTransaction extends javax.swing.JFrame {
    
    private String filename;
    private File caseDoc;

    /**
     * Creates new form AddTransaction
     */
    public AddTransaction() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FileNameLabel = new javax.swing.JLabel();
        caseNum = new javax.swing.JTextField();
        Status = new javax.swing.JTextField();
        caseTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Browse = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 740));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FileNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FileNameLabel.setForeground(new java.awt.Color(102, 102, 102));
        FileNameLabel.setText("Add Attachment....");
        getContentPane().add(FileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 380, 50));

        caseNum.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(caseNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 216, 312, 50));

        Status.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 316, 312, 50));

        caseTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        getContentPane().add(caseTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 417, 312, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/addTransaction.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        Browse.setBackground(new java.awt.Color(204, 204, 204));
        Browse.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Browse.setText("Choose File");
        Browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseActionPerformed(evt);
            }
        });
        getContentPane().add(Browse, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 190, 50));

        Add.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Add.setText("add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 330, 50));

        back.setText("jLabel1");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseActionPerformed
        
        filename = FileChooser.pickAFile();
        caseDoc = new File(filename);
        File currentDirFile = new File("Transactions\\" + caseDoc.getName());
        try {
            Files.copy(caseDoc.toPath(), currentDirFile.toPath(), REPLACE_EXISTING);
        } catch (IOException ex) {
            Logger.getLogger(AddTransaction.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        FileNameLabel.setForeground(Color.black);
        FileNameLabel.setText(caseDoc.getName());

    }//GEN-LAST:event_BrowseActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        try {
            
            if (caseNum.getText().isEmpty() || caseTitle.getText().isEmpty()
                    || Status.getText().isEmpty()) {
                throw new Exception("You MUST fill All the required feilds!!");
            } else {
                Transaction.ReadTranInformations();
                
                Transaction.AddTransaction("TransactionFile.txt",
                        new Transaction(caseNum.getText(), caseTitle.getText(), ("Transactions\\" + caseDoc.getName()), Status.getText()));
                
                JOptionPane.showMessageDialog(null, "The Transaction has been Added succefully");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

    }//GEN-LAST:event_AddActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Browse;
    private javax.swing.JLabel FileNameLabel;
    private javax.swing.JTextField Status;
    private javax.swing.JLabel back;
    private javax.swing.JTextField caseNum;
    private javax.swing.JTextField caseTitle;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
