/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RandJLawFirm;

import static RandJLawFirm.FileChooser.getMediaDirectory;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.util.Vector;

public class DeletTransaction extends javax.swing.JFrame {

    File CaseFile;
    int index = -1;

    public void TableContent() throws FileNotFoundException {

        // Set Table Rows and Columns Sizes
        CaseInfo.setRowHeight(20);
        TableColumnModel columnModel = CaseInfo.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(50);
        columnModel.getColumn(1).setPreferredWidth(50);
        columnModel.getColumn(2).setPreferredWidth(10);
        columnModel.getColumn(3).setPreferredWidth(10);
        // declare table variable to start fill the table with Transaction information
        DefaultTableModel model = (DefaultTableModel) CaseInfo.getModel();
        // clear table from any values 
        model.setRowCount(0);
        // fill Transaction arraylist
        Transaction.ReadTranInformations();
        // insert Transaction information into the table 
        for (int i = 0; i < Transaction.getTransactions().size(); i++) {
            Vector row = new Vector();

            row.add(Transaction.getTransactions().get(i).getCaseNumber());
            row.add(Transaction.getTransactions().get(i).getCaseTitle());
            CaseFile = new File(Transaction.getTransactions().get(i).getCaseDoc());
            row.add(CaseFile.getName());

            row.add(Transaction.getTransactions().get(i).getStatus());

            model.addRow(row);
        }
    }

    public DeletTransaction() throws FileNotFoundException {
        initComponents();
        TableContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Info = new javax.swing.JScrollPane();
        CaseInfo = new javax.swing.JTable();
        Interface = new javax.swing.JLabel();
        DeleteTrans = new javax.swing.JButton();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CaseInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CaseInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "       Case number", "       Case title", "     Case Document", "       Statu"
            }
        ));
        CaseInfo.setFillsViewportHeight(true);
        CaseInfo.setRowHeight(18);
        CaseInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaseInfoMouseClicked(evt);
            }
        });
        CaseInfo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                CaseInfoInputMethodTextChanged(evt);
            }
        });
        Info.setViewportView(CaseInfo);

        getContentPane().add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 930, 380));

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/DeleteTransaction.png"))); // NOI18N
        Interface.setText("jLabel1");
        getContentPane().add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        DeleteTrans.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        DeleteTrans.setText("Delete");
        DeleteTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTransActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 630, 350, 45));

        Back.setText("jLabel1");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaseInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaseInfoMouseClicked
        index = CaseInfo.getSelectedRow();
    }//GEN-LAST:event_CaseInfoMouseClicked

    private void CaseInfoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_CaseInfoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CaseInfoInputMethodTextChanged

    private void DeleteTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTransActionPerformed
        // TODO add your handling code here:
        try {
            if (index == -1) {
                // In case user press "delete" button while user didn't choose client to delete
                JOptionPane.showConfirmDialog(null,
                        "You Did Not Select Transaction to Delete",
                        "Select Transaction", JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                int choice = JOptionPane.showConfirmDialog(null,
                        "Are you Sure You Want to Delete " + "Case No " + Transaction.getTransactions().get(index).getCaseNumber() + "  Case Title "
                        + Transaction.getTransactions().get(index).getCaseTitle() + " ?",
                        "Confirm Case Deletion", JOptionPane.YES_NO_OPTION,
                        JOptionPane.ERROR_MESSAGE);

                if (choice == JOptionPane.YES_OPTION) {
                    // delete from the file "Our Database"
                    Transaction.DeleteTrans(index * 4);
                    // delete from the arraylist
                    Transaction.getTransactions().remove(index);
                    // set all things back
                    index = -1;
                    TableContent();
                }
                if (choice == JOptionPane.NO_OPTION) {
                    // user don't want to delete the Transaction
                    // set all things back
                    index = -1;
                    TableContent();
                }

            }

        } catch (IOException ex) {
            Logger.getLogger(DeletTransaction.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DeleteTransActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
new HomePage().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeletTransaction().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DeletTransaction.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JTable CaseInfo;
    private javax.swing.JButton DeleteTrans;
    private javax.swing.JScrollPane Info;
    private javax.swing.JLabel Interface;
    // End of variables declaration//GEN-END:variables
}
