/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RandJLawFirm;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author iijoo
 */
public class DeleteClient extends javax.swing.JFrame {

    int index = -1;

    public void TableContent() throws FileNotFoundException {

        // Set Table Rows and Columns Sizes
        ClientsInformation.setRowHeight(20);
        TableColumnModel columnModel = ClientsInformation.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(30);
        columnModel.getColumn(2).setPreferredWidth(7);
        columnModel.getColumn(3).setPreferredWidth(30);
        columnModel.getColumn(4).setPreferredWidth(35);
        columnModel.getColumn(5).setPreferredWidth(130);
        columnModel.getColumn(6).setPreferredWidth(80);
        // declare table variable to start fill the table with clients information
        DefaultTableModel ClientsTable = (DefaultTableModel) ClientsInformation.getModel();
        // clear table from any values 
        ClientsTable.setRowCount(0);
        // fill clients arraylist
        Client.ReadInformations();
        // insert clients information into the table 
        for (int i = 0; i < Client.getClients().size(); i++) {
            Vector row = new Vector();
            row.add(Client.getClients().get(i).getFirstName());
            row.add(Client.getClients().get(i).getLastName());
            row.add(Client.getClients().get(i).getGender());
            row.add(Client.getClients().get(i).getPhone());
            row.add(Client.getClients().get(i).getSSN());
            row.add(Client.getClients().get(i).getEmail());
            row.add(Client.getClients().get(i).getBankIBAN());
            ClientsTable.addRow(row);
        }
        

    }

    public DeleteClient() throws FileNotFoundException {
        initComponents();
        TableContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        ClientsInformation = new javax.swing.JTable();
        Interface = new javax.swing.JLabel();
        Delete = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ClientsInformation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClientsInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Phone Number", "SSN", "Email", "Bank Account Number"
            }
        ));
        ClientsInformation.setFillsViewportHeight(true);
        ClientsInformation.setRowHeight(18);
        ClientsInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsInformationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ClientsInformation);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 214, 915, 367));

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/DeleteClient.png"))); // NOI18N
        Interface.setText("jLabel1");
        getContentPane().add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 700));

        Delete.setText("Delete Client");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 620, 350, 60));

        back.setText("jLabel1");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientsInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsInformationMouseClicked
        index = ClientsInformation.getSelectedRow();
    }//GEN-LAST:event_ClientsInformationMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            if (index == -1) {
                // In case user press "delete" button while user didn't choose client to delete
                JOptionPane.showConfirmDialog(null,
                        "You Did Not Select Client to Delete",
                        "Select Client", JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                int choice = JOptionPane.showConfirmDialog(null,
                        "Are you Sure You Want to Delete " + Client.getClients().get(index).getFirstName() + " "
                        + Client.getClients().get(index).getLastName() + " ?",
                        "Confirm Client Deletion", JOptionPane.YES_NO_OPTION,
                        JOptionPane.ERROR_MESSAGE);

                if (choice == JOptionPane.YES_OPTION) {
                    // delete from the file "Our Database"
                    Client.DeleteClientInformationOnDB(index * 7);
                    // delete from the arraylist
                    Client.getClients().remove(index);
                    // set all things back
                    index = -1;
                    TableContent();
                }
                if (choice == JOptionPane.NO_OPTION) {
                    // user don't want to delete the client
                    // set all things back
                    index = -1;
                    TableContent();
                }

            }

        } catch (IOException ex) {
            Logger.getLogger(DeleteClient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new HomePage().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeleteClient().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DeleteClient.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientsInformation;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Interface;
    private javax.swing.JLabel back;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
