package RandJLawFirm;

import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class GeneratReport extends javax.swing.JFrame {

    File myObj;

    public GeneratReport() {
        Employee.AllEmployees();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Interface = new javax.swing.JLabel();
        usereport = new javax.swing.JButton();
        transReport = new javax.swing.JButton();
        clientReport = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/GenerateReport.png"))); // NOI18N
        jPanel1.add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        usereport.setText("Genrate user report ");
        usereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usereportActionPerformed(evt);
            }
        });
        jPanel1.add(usereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 430, 70));

        transReport.setText("Genrate transaction report ");
        transReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transReportActionPerformed(evt);
            }
        });
        jPanel1.add(transReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 430, 90));

        clientReport.setText("Genrate client report ");
        clientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientReportActionPerformed(evt);
            }
        });
        jPanel1.add(clientReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 430, 60));

        back.setText("jLabel1");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientReportActionPerformed
        PrintWriter writer = null;
        try {
            myObj = new File("Client Report.txt");
            writer = new PrintWriter("Client Report.txt");
            writer.println(Client.GenerateClientsReport());
            writer.flush();
            writer.close();

            // OPEN GENERATED REPORT
            OpenReport();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(GeneratReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clientReportActionPerformed

    private void transReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transReportActionPerformed
        PrintWriter writer = null;
        try {
            myObj = new File("Transaction Report.txt");
            writer = new PrintWriter("Transaction Report.txt");

            writer.println(Transaction.GenerateTransactionsReport());

            writer.flush();
            writer.close();

            // OPEN GENERATED REPORT
            OpenReport();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(GeneratReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_transReportActionPerformed

    private void usereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usereportActionPerformed

        PrintWriter writer = null;
        try {
            myObj = new File("User Report.txt");
            writer = new PrintWriter("User Report.txt");
            writer.println(User.GenerateUserReport());
            writer.flush();
            writer.close();

            // OPEN GENERATED REPORT
            OpenReport();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(GeneratReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_usereportActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    public void OpenReport() {
        JOptionPane.showMessageDialog(this, "Your Reporet Has Been Generated Successfully",
                "Report Generated",
                JOptionPane.INFORMATION_MESSAGE);
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.open(myObj);
        } catch (IOException ex) {
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Interface;
    private javax.swing.JLabel back;
    private javax.swing.JButton clientReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton transReport;
    private javax.swing.JButton usereport;
    // End of variables declaration//GEN-END:variables
}
