/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RandJLawFirm;

import static RandJLawFirm.Client.Clients;
import static RandJLawFirm.Transaction.transactions;
import static RandJLawFirm.User.UserDb;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author farah
 */
public class generatReport extends javax.swing.JFrame {

    /**
     * Creates new form generatReport
     */
    File CaseFile;

    public generatReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Interface = new javax.swing.JLabel();
        usereport = new javax.swing.JButton();
        transReport = new javax.swing.JButton();
        clientReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/reoprtttt.png"))); // NOI18N
        jPanel1.add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        usereport.setText("Genrate user report ");
        usereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usereportActionPerformed(evt);
            }
        });
        jPanel1.add(usereport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 430, 70));

        transReport.setText("Genrate transaction report ");
        transReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transReportActionPerformed(evt);
            }
        });
        jPanel1.add(transReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 430, 90));

        clientReport.setText("Genrate client report ");
        clientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientReportActionPerformed(evt);
            }
        });
        jPanel1.add(clientReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 430, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientReportActionPerformed
        PrintWriter writer = null;
        try {
            File myObj = new File("Client Report.txt");
            writer = new PrintWriter("Client Report.txt");
            writer.println("=============================================================================");
            writer.println("=========================== R & J LAW FIRM ==================================");
            writer.println("=============================================================================");
            writer.println("========================== CLIENTS REPORT ====================================");
            java.util.Date date = new java.util.Date();
            writer.println("===================   " + date + "   =========================");
            writer.println("=============================================================================");
            writer.println(" ");
            // fill clients arraylist
            Client.ReadInformations();
            for (int i = 0; i < Clients.size(); i++) {
                writer.println("       Full name: " + Clients.get(i).getFirstName() + " " + Clients.get(i).getLastName());
                writer.println("       Gender:    " + Clients.get(i).getGender() + "            Phonenumber: " + Clients.get(i).getPhone());
                writer.println("       SSN:       " + Clients.get(i).getSSN() + "      Email:       " + Clients.get(i).getEmail());
                writer.println("       BankIBAN   " + Clients.get(i).getBankIBAN());
                writer.println("=============================================================================");

                System.out.println("client report done succsuflly");
            }
            writer.flush();
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(generatReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_clientReportActionPerformed

    private void transReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transReportActionPerformed
        PrintWriter writer = null;
        try {
            File myObj = new File("Transaction Report.txt");
            writer = new PrintWriter("Transaction Report.txt");
            writer.println("=============================================================================");
            writer.println("=========================== R & J LAW FIRM ==================================");
            writer.println("=============================================================================");
            writer.println("======================== TRANSACTIONS REPORT =================================");
            java.util.Date date = new java.util.Date();
            writer.println("===================   " + date + "   =========================");
            writer.println("=============================================================================");

            // fill arraylist
            Transaction.ReadTranInformations();
            for (int i = 0; i < Transaction.getTransactions().size(); i++) {
                writer.println("      Case number:             " + Transaction.getTransactions().get(i).getCaseNumber() + "                  Case title:   " + Transaction.getTransactions().get(i).getCaseTitle());
                CaseFile = new File(Transaction.getTransactions().get(i).getCaseDoc());
                writer.println("      Case document:       " + CaseFile.getName() + "       Case status:    " + Transaction.getTransactions().get(i).getStatus());
                writer.println("=============================================================================");
                writer.println(" ");
                System.out.println("Transaction report done succsuflly");
            }
            writer.flush();
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(generatReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_transReportActionPerformed

    private void usereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usereportActionPerformed

        PrintWriter writer = null;
        try {
            File myObj = new File("User Report.txt");
            writer = new PrintWriter("User Report.txt");
            writer.println("=============================================================================");
            writer.println("=========================== R & J LAW FIRM ==================================");
            writer.println("=============================================================================");
            writer.println("============================ USER REPORT ====================================\n");
            java.util.Date date = new java.util.Date();
            writer.println("===================   " + date + "   =========================");
            writer.println("=============================================================================");

            // fill  arraylist
            User.ReadInformations();
            Employee CurrentEmployee = null;
            for (int i = 0; i < User.UserDb.size(); i++) {
                for (int j = 0; j < Employee.getEmployees().size(); j++) {
                    if (Employee.getEmployees().get(j).getID().equals(User.UserDb.get(i).getID())) {
                        CurrentEmployee = Employee.getEmployees().get(j);
                        break;
                    }
                }
                writer.println("      ID:  " + User.UserDb.get(i).getID() + "                  Email:   " + User.UserDb.get(i).email);
                writer.println("       First Name: " + CurrentEmployee.getFname());
                writer.println("        Last Name: " + CurrentEmployee.getLname());
                writer.println("     Phone Number: " + CurrentEmployee.getPhone());
                if (CurrentEmployee.getIsManager()) {
                    writer.println("     Position: " + "Manager");
                } else {
                    writer.println("     Position: " + "Employee");
                }
                writer.println("=============================================================================");
                System.out.println("User report done succsuflly");
            }
            writer.flush();
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(generatReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_usereportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(generatReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(generatReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(generatReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(generatReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new generatReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Interface;
    private javax.swing.JButton clientReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton transReport;
    private javax.swing.JButton usereport;
    // End of variables declaration//GEN-END:variables
}
