package RandJLawFirm;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class HomePage extends javax.swing.JFrame {

    private Employee CurrentEmployee = null;

    public HomePage() {
        Employee.AllEmployees();
        for (int i = 0; i < Employee.getEmployees().size(); i++) {
            if (Employee.getEmployees().get(i).getID().equals(User.getCurrentUserID())) {
                CurrentEmployee = Employee.getEmployees().get(i);
            }
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Interface = new javax.swing.JLabel();
        AddClient = new javax.swing.JButton();
        ModifyClient = new javax.swing.JButton();
        DeleteClient = new javax.swing.JButton();
        back = new javax.swing.JLabel();
        SignOut = new javax.swing.JLabel();
        AddTransaction = new javax.swing.JLabel();
        ModifyTransaction = new javax.swing.JLabel();
        ViewCaseDetails = new javax.swing.JLabel();
        AddUser = new javax.swing.JLabel();
        deleteTransaction = new javax.swing.JLabel();
        GenerateReport = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/HomePage.png"))); // NOI18N
        Interface.setText("jLabel1");
        Interface.setPreferredSize(new java.awt.Dimension(950, 700));
        getContentPane().add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 700));

        AddClient.setText("Add Client");
        AddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientActionPerformed(evt);
            }
        });
        getContentPane().add(AddClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 330, 60));

        ModifyClient.setText("Modify Client");
        ModifyClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyClientActionPerformed(evt);
            }
        });
        getContentPane().add(ModifyClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 330, 60));

        DeleteClient.setText("Delete Client");
        DeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClientActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 330, 70));

        back.setText("jLabel1");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 50));

        SignOut.setText("jLabel1");
        SignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignOutMouseClicked(evt);
            }
        });
        getContentPane().add(SignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 330, 50));

        AddTransaction.setText("jLabel1");
        AddTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddTransactionMouseClicked(evt);
            }
        });
        getContentPane().add(AddTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 320, 50));

        ModifyTransaction.setText("jLabel1");
        ModifyTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifyTransactionMouseClicked(evt);
            }
        });
        getContentPane().add(ModifyTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 320, 60));

        ViewCaseDetails.setText("jLabel1");
        ViewCaseDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCaseDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(ViewCaseDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 320, 50));

        AddUser.setText("jLabel1");
        AddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserMouseClicked(evt);
            }
        });
        getContentPane().add(AddUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 320, 60));

        deleteTransaction.setText("jLabel1");
        deleteTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteTransactionMouseClicked(evt);
            }
        });
        getContentPane().add(deleteTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 320, 60));

        GenerateReport.setText("jLabel1");
        GenerateReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerateReportMouseClicked(evt);
            }
        });
        getContentPane().add(GenerateReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 320, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientActionPerformed
        new addClient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddClientActionPerformed

    private void ModifyClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyClientActionPerformed
        try {
            new ModifyClient().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ModifyClientActionPerformed

    private void DeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClientActionPerformed
        try {
            new DeleteClient().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_DeleteClientActionPerformed

    private void SignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignOutMouseClicked

        new FirstWindow().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_SignOutMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new LogIn().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backMouseClicked

    private void AddTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddTransactionMouseClicked
        new AddTransaction().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddTransactionMouseClicked

    private void ModifyTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifyTransactionMouseClicked
        try {
            new modifyTransaction().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_ModifyTransactionMouseClicked

    private void ViewCaseDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCaseDetailsMouseClicked

        if (CurrentEmployee.getIsManager()) {
            try {
                new SearchCase().setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Only Manager Can Access This Page", "Cannot Access", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_ViewCaseDetailsMouseClicked

    private void AddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserMouseClicked
        if (CurrentEmployee.getIsManager()) {
            new addUser().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Only Manager Can Access This Page", "Cannot Access", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddUserMouseClicked

    private void deleteTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteTransactionMouseClicked
        try {
            new DeletTransaction().setVisible(true);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_deleteTransactionMouseClicked

    private void GenerateReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerateReportMouseClicked

        if (CurrentEmployee.getIsManager()) {
            new generatReport().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Only Manager Can Access This Page", "Cannot Access", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_GenerateReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClient;
    private javax.swing.JLabel AddTransaction;
    private javax.swing.JLabel AddUser;
    private javax.swing.JButton DeleteClient;
    private javax.swing.JLabel GenerateReport;
    private javax.swing.JLabel Interface;
    private javax.swing.JButton ModifyClient;
    private javax.swing.JLabel ModifyTransaction;
    private javax.swing.JLabel SignOut;
    private javax.swing.JLabel ViewCaseDetails;
    private javax.swing.JLabel back;
    private javax.swing.JLabel deleteTransaction;
    // End of variables declaration//GEN-END:variables
}
