package RandJLawFirm;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author iijoo
 */
public class ModifyClient extends javax.swing.JFrame {

    /**
     * Creates new form ModifyClient
     */
    int index = -1; // For Mouse click event on the table

    public void TableContent() throws FileNotFoundException {

        // Set Table Rows and Columns Sizes
        ClientsInformation.setRowHeight(20);
        TableColumnModel columnModel = ClientsInformation.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(30);
        columnModel.getColumn(1).setPreferredWidth(30);
        columnModel.getColumn(2).setPreferredWidth(7);
        columnModel.getColumn(3).setPreferredWidth(30);
        columnModel.getColumn(4).setPreferredWidth(35);
        columnModel.getColumn(5).setPreferredWidth(130);
        columnModel.getColumn(6).setPreferredWidth(80);
        // declare table variable to start fill the table with clients information
        DefaultTableModel ClientsTable = (DefaultTableModel) ClientsInformation.getModel();
        // clear table from any values 
        ClientsTable.setRowCount(0);
        // fill clients arraylist
        Client.ReadInformations();
        // insert clients information into the table 
        for (int i = 0; i < Client.Clients.size(); i++) {
            Vector row = new Vector();

            row.add(Client.Clients.get(i).getFirstName());
            row.add(Client.Clients.get(i).getLastName());
            row.add(Client.Clients.get(i).getGender());
            row.add(Client.Clients.get(i).getPhone());
            row.add(Client.Clients.get(i).getSSN());
            row.add(Client.Clients.get(i).getEmail());
            row.add(Client.Clients.get(i).getBankIBAN());
            ClientsTable.addRow(row);
        }

    }

    public ModifyClient() throws FileNotFoundException {
        initComponents();
        TableContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientsInformation1 = new javax.swing.JTable();
        email = new javax.swing.JTextField();
        iban = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox();
        fName = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        SSN = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        ClientsInformation = new javax.swing.JTable();
        Interface = new javax.swing.JLabel();
        Modify = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        ClientsInformation1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Phone Number", "SSN", "Email", "Bank Account Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ClientsInformation1.setName("Clients Information"); // NOI18N
        ClientsInformation1.getTableHeader().setReorderingAllowed(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(970, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 526, 190, 41));

        iban.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        iban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibanActionPerformed(evt);
            }
        });
        getContentPane().add(iban, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 608, 233, 41));

        gender.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F", "" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 607, 80, 40));

        fName.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        fName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameActionPerformed(evt);
            }
        });
        getContentPane().add(fName, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 526, 190, 41));

        LName.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });
        getContentPane().add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 526, 190, 41));

        phone.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 608, 190, 41));

        SSN.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        SSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNActionPerformed(evt);
            }
        });
        getContentPane().add(SSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 526, 190, 41));

        ClientsInformation.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClientsInformation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Gender", "Phone Number", "SSN", "Email", "Bank Account Number"
            }
        ));
        ClientsInformation.setFillsViewportHeight(true);
        ClientsInformation.setRowHeight(18);
        ClientsInformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsInformationMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ClientsInformation);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 210, 914, 224));

        Interface.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/ModifyClient.png"))); // NOI18N
        Interface.setText("jLabel8");
        getContentPane().add(Interface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Modify.setText("Modify");
        Modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyActionPerformed(evt);
            }
        });
        getContentPane().add(Modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 619, 150, 60));

        back.setText("jLabel1");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 40, 50, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void ibanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibanActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void SSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSNActionPerformed

    private void ClientsInformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsInformationMouseClicked

        // -------------------------------------------------------------
        // STEP 1 : get values in selected row
        index = ClientsInformation.getSelectedRow();
        TableModel tableModel = ClientsInformation.getModel();

        // ----------------------------------------------------------------
        // STEP 2 : show selected row on the text fields to user to modify 
        fName.setText(Client.Clients.get(index).getFirstName());
        LName.setText(Client.Clients.get(index).getLastName());
        gender.setSelectedItem(Client.Clients.get(index).getGender() + "");
        SSN.setText(Client.Clients.get(index).getSSN());
        email.setText(Client.Clients.get(index).getEmail());
        phone.setText(Client.Clients.get(index).getPhone());
        iban.setText(Client.Clients.get(index).getBankIBAN());


    }//GEN-LAST:event_ClientsInformationMouseClicked

    private void ModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyActionPerformed

        try {
            // Check each text field value with our clients data on the array list
            // to modify just the values that the user changed it
            boolean changeFound = false;// to print massage to user 

            if (index == -1) {
                // In case user press "Modify" button while user didn't choose client to Modify
                JOptionPane.showConfirmDialog(null,
                        "You Did Not Select Client to Modify",
                        "Select Client", JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (!fName.getText().equals(Client.Clients.get(index).getFirstName())) {
                    // The method will only overwrite on previous value on the file
                    Client.ModifyClientInformationOnDB((index * 7) + 1, fName.getText());
                    // modify on arraylist
                    Client.Clients.get(index).setFirstName(fName.getText());
                    changeFound = true;
                }
                if (!LName.getText().equals(Client.Clients.get(index).getLastName())) {
                    Client.ModifyClientInformationOnDB((index * 7) + 2, LName.getText());
                    Client.Clients.get(index).setLastName(LName.getText());
                    changeFound = true;
                }
                if (!SSN.getText().equals(Client.Clients.get(index).getSSN())) {
                    Client.ModifyClientInformationOnDB((index * 7) + 3, SSN.getText());
                    Client.Clients.get(index).setSSN(SSN.getText());
                    changeFound = true;
                }
                if (!email.getText().equals(Client.Clients.get(index).getEmail())) {
                    Client.ModifyClientInformationOnDB((index * 7) + 4, email.getText());
                    Client.Clients.get(index).setEmail(email.getText());
                    changeFound = true;
                }
                if (!phone.getText().equals(Client.Clients.get(index).getPhone())) {
                    Client.ModifyClientInformationOnDB((index * 7) + 5, phone.getText());
                    Client.Clients.get(index).setPhone(phone.getText());
                    changeFound = true;
                }
                if (!iban.getText().equals(Client.Clients.get(index).getBankIBAN())) {
                    Client.ModifyClientInformationOnDB((index * 7) + 6, iban.getText());
                    Client.Clients.get(index).setBankIBAN(iban.getText());
                    changeFound = true;
                }
                if (gender.getSelectedItem().toString().charAt(0) != Client.Clients.get(index).getGender()) {
                    Client.ModifyClientInformationOnDB((index * 7) + 7, gender.getSelectedItem().toString());
                    Client.Clients.get(index).setGender(gender.getSelectedItem().toString().charAt(0));
                    changeFound = true;
                }

                if (changeFound) {
                    JOptionPane.showMessageDialog(null, "Client Information has been Modified successfully");
                    TableContent();// to update table with changes
                }
                if (!changeFound) {
                    JOptionPane.showMessageDialog(null, "You did not commit any modifications");
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(ModifyClient.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ModifyActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked

        new HomePage().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ModifyClient().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ModifyClient.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientsInformation;
    private javax.swing.JTable ClientsInformation1;
    private javax.swing.JLabel Interface;
    private javax.swing.JTextField LName;
    private javax.swing.JButton Modify;
    private javax.swing.JTextField SSN;
    private javax.swing.JLabel back;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fName;
    private javax.swing.JComboBox gender;
    private javax.swing.JTextField iban;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
